let menu = [
  {
    lastModifiedDate: "2021-12-22",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 128,
    icon: "1",
    name: "Settlement Management",
    menuCode: "",
    orderId: 1,
    parentId: 0,
    uri: "gateway/settlement",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2021-12-22",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 129,
        icon: "1",
        name: "Settlement Bank Setup",
        menuCode: "",
        orderId: 14,
        parentId: 128,
        uri: "gateway/settlement/settlement-bank-account-setup",
        menuType: "OUR_MENU",
        children: [
          {
            uri: "sudiptamang",
          },
        ],
        menuPrefix: null,
        active: true,
        created_date: "2021-12-16",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-01-04",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 134,
        icon: "1",
        name: "Settlement GL Setup",
        menuCode: "",
        orderId: 1,
        parentId: 128,
        uri: "gateway/settlement/settlement-gl-setup",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-01-04",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2021-12-22",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 115,
        icon: "1",
        name: "Co-operative Bank Setup",
        menuCode: "",
        orderId: 1,
        parentId: 128,
        uri: "gateway/settlement/coop-bank-setup",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-10-11",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2021-12-16",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2022-01-17",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 138,
    icon: "1",
    name: "Commission Management",
    menuCode: "",
    orderId: 1,
    parentId: 0,
    uri: "gateway/",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2022-07-25",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 133,
        icon: "1",
        name: "Remit Commission Setup",
        menuCode: "",
        orderId: 1,
        parentId: 138,
        uri: "gateway/remit-commission-management",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-12-24",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-01-17",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 139,
        icon: "1",
        name: "Utility Commission Setup",
        menuCode: "",
        orderId: 1,
        parentId: 138,
        uri: "gateway/commission-management",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-01-17",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-03-22",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 195,
        icon: "1",
        name: "Merchant Commission Setup",
        menuCode: "",
        orderId: 1,
        parentId: 138,
        uri: "gateway/merchant-commission-setup",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-03-22",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2022-01-17",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2021-01-29",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 11,
    icon: null,
    name: "Client Management",
    menuCode: null,
    orderId: 1,
    parentId: 0,
    uri: "gateway/client-management",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2022-08-02",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 13,
        icon: null,
        name: "Client Setup",
        menuCode: null,
        orderId: 1,
        parentId: 11,
        uri: "gateway/client-management",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2020-03-26",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2020-03-25",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2021-03-05",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 19,
    icon: null,
    name: "Internal Recharge Management",
    menuCode: null,
    orderId: 1,
    parentId: 0,
    uri: "gateway/internal-recharge-management",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2022-07-25",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 21,
        icon: null,
        name: "Internal Staff Recharge ",
        menuCode: null,
        orderId: 2,
        parentId: 19,
        uri: "gateway/internal-recharge-management/internal-recharge",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-03-05",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-07-25",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 20,
        icon: null,
        name: "Internal Staff Setup",
        menuCode: null,
        orderId: 1,
        parentId: 19,
        uri: "gateway/internal-recharge-management/internal-staff",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-03-05",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2021-03-05",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2021-05-25",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 51,
    icon: null,
    name: "Service Management",
    menuCode: null,
    orderId: 1,
    parentId: 0,
    uri: "gateway/service-management",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2022-08-02",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 71,
        icon: null,
        name: "Service Group Setup",
        menuCode: null,
        orderId: 4,
        parentId: 51,
        uri: "gateway/service-management/service-groups",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-06-30",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-07-15",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 70,
        icon: null,
        name: "Client Service Switch",
        menuCode: null,
        orderId: 3,
        parentId: 51,
        uri: "gateway/service-management/client-service",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-06-30",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-08-02",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 53,
        icon: null,
        name: "Service Action Setup",
        menuCode: null,
        orderId: 2,
        parentId: 51,
        uri: "gateway/service-management/service-actions",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-05-25",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-08-02",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 52,
        icon: null,
        name: "Vendor Service Mapping",
        menuCode: null,
        orderId: 1,
        parentId: 51,
        uri: "gateway/service-management/vendor-service",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-05-25",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2021-05-25",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2021-05-01",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 28,
    icon: null,
    name: "Send Notification",
    menuCode: null,
    orderId: 1,
    parentId: 0,
    uri: "gateway/send-notification",
    menuType: "OUR_MENU",
    children: [],
    menuPrefix: null,
    active: true,
    created_date: "2021-05-01",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2021-05-01",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 36,
    icon: null,
    name: "Digital Financial Service",
    menuCode: null,
    orderId: 1,
    parentId: 0,
    uri: "gateway/digital-financial-service",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2021-05-01",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 40,
        icon: null,
        name: "Our Charge Setup",
        menuCode: null,
        orderId: 4,
        parentId: 36,
        uri: "gateway/digital-financial-service/our-charge-setup",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-05-01",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2021-05-02",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 41,
        icon: null,
        name: "Client Charge Setup",
        menuCode: null,
        orderId: 3,
        parentId: 36,
        uri: "gateway/digital-financial-service/client-charge-setup",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-05-02",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2021-05-01",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 39,
        icon: null,
        name: "Client Service Mapping",
        menuCode: null,
        orderId: 4,
        parentId: 36,
        uri: "gateway/digital-financial-service/client-service-mapping",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-05-01",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2021-06-17",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 64,
        icon: null,
        name: "Hub Charge Setup",
        menuCode: null,
        orderId: 1,
        parentId: 36,
        uri: "gateway/digital-financial-service/hub-charge-setup",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-06-17",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2021-06-24",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 67,
        icon: null,
        name: "Customer Charge Setup",
        menuCode: null,
        orderId: 7,
        parentId: 36,
        uri: "gateway/digital-financial-service/customer-charge-setup",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-06-24",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-08-02",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 37,
        icon: null,
        name: "Service Provider Setup",
        menuCode: null,
        orderId: 1,
        parentId: 36,
        uri: "gateway/digital-financial-service/service-providers",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-05-01",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-08-02",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 38,
        icon: null,
        name: "Service Option Setup",
        menuCode: null,
        orderId: 2,
        parentId: 36,
        uri: "gateway/digital-financial-service/service-options",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-05-01",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2021-05-01",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2021-05-21",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 15,
    icon: null,
    name: "Vendor Management",
    menuCode: null,
    orderId: 2,
    parentId: 0,
    uri: "gateway/vendor-management",
    menuType: "OUR_MENU",
    children: [],
    menuPrefix: null,
    active: true,
    created_date: "2020-03-28",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2021-11-29",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 120,
    icon: "1",
    name: "Transaction Limit Managment",
    menuCode: "",
    orderId: 1,
    parentId: 0,
    uri: "gateway/transaction-limit-management",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2021-12-24",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 119,
        icon: "1",
        name: "Prefunding Limit",
        menuCode: "",
        orderId: 1,
        parentId: 120,
        uri: "gateway/transaction-limit-management/prefunding-limit",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-11-26",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2021-12-03",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 122,
        icon: "1",
        name: "User Scope Mapping",
        menuCode: "",
        orderId: 1,
        parentId: 120,
        uri: "gateway/transaction-limit-management/user-scope-mapping",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-12-03",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-02-10",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 137,
        icon: "1",
        name: "Prefunding Limit Report",
        menuCode: "",
        orderId: 1,
        parentId: 120,
        uri: "gateway/prefunding-limit-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-01-17",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2021-11-29",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2022-08-08",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 23,
    icon: null,
    name: "Cooperative Services",
    menuCode: null,
    orderId: 1,
    parentId: 0,
    uri: "gateway/bank-transfer/ibft-setup",
    menuType: "OUR_MENU",
    children: [],
    menuPrefix: null,
    active: true,
    created_date: "2021-04-18",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2021-05-22",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 47,
    icon: null,
    name: "Reports",
    menuCode: null,
    orderId: 1,
    parentId: 0,
    uri: "gateway/",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2021-05-22",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 48,
        icon: null,
        name: "Flight Booking Report",
        menuCode: null,
        orderId: 1,
        parentId: 47,
        uri: "gateway/request-response/flight-booking",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2021-05-22",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2021-05-22",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 49,
        icon: null,
        name: "Internal Fund Transfer Report",
        menuCode: null,
        orderId: 1,
        parentId: 47,
        uri: "gateway/request-response/internal-fund-transfer",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2021-05-22",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2021-05-24",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 50,
        icon: null,
        name: "Outgoing Report",
        menuCode: null,
        orderId: 1,
        parentId: 47,
        uri: "gateway/sms-report/outgoing",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2021-05-24",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2021-05-27",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 55,
        icon: null,
        name: "Reconciliation Report",
        menuCode: null,
        orderId: 1,
        parentId: 47,
        uri: "gateway/recharge-report/reconciliation-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2021-05-27",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2021-05-31",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 56,
        icon: null,
        name: "Transaction Report",
        menuCode: null,
        orderId: 6,
        parentId: 47,
        uri: "gateway/recharge-report/transaction-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2021-05-31",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2021-05-31",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 57,
        icon: null,
        name: "Commission Report",
        menuCode: null,
        orderId: 7,
        parentId: 47,
        uri: "gateway/recharge-report/commission-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2021-05-31",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2021-06-04",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 62,
        icon: null,
        name: "Current Balance Report",
        menuCode: null,
        orderId: 8,
        parentId: 47,
        uri: "gateway/recharge-report/current-balance",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2021-06-04",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2021-07-07",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 76,
        icon: null,
        name: "IBFT and Wallet Report",
        menuCode: null,
        orderId: 11,
        parentId: 47,
        uri: "gateway/request-response/ibft-and-wallet",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2021-07-07",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2021-06-28",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 68,
        icon: null,
        name: "Topup Credit Log Report",
        menuCode: null,
        orderId: 9,
        parentId: 47,
        uri: "gateway/recharge-report/topup-credit",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2021-06-28",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-10-19",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 190,
        icon: "1",
        name: "Merchant Payment Report",
        menuCode: "",
        orderId: 1,
        parentId: 47,
        uri: "gateway/merchant-payment-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2022-02-25",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-03-03",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 192,
        icon: "1",
        name: "Remit Reconciliation Report",
        menuCode: "",
        orderId: 1,
        parentId: 47,
        uri: "gateway/remit-reconciliation-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2022-03-03",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2023-02-15",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 251,
        icon: null,
        name: "Utility Reconciliation Report",
        menuCode: "",
        orderId: 1,
        parentId: 47,
        uri: "gateway/utility-reconciliation-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2023-02-15",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-04-28",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 209,
        icon: "1",
        name: "Summary Report",
        menuCode: "",
        orderId: 1,
        parentId: 47,
        uri: "gateway/summary-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2022-04-28",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-06-10",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 211,
        icon: "20",
        name: "SMS Credit Log Report",
        menuCode: "",
        orderId: 1,
        parentId: 47,
        uri: "gateway/sms-credit-log-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2022-06-10",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-10-19",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 207,
        icon: "1",
        name: "DFS Pending Transaction",
        menuCode: "",
        orderId: 1,
        parentId: 47,
        uri: "gateway/dfs-pending-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2022-04-13",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-10-19",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 205,
        icon: "4",
        name: "School Payment Report",
        menuCode: "",
        orderId: 3,
        parentId: 47,
        uri: "gateway/merchant-school-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2022-04-01",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-07-19",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 218,
        icon: null,
        name: "User Wise Transaction Report",
        menuCode: "",
        orderId: 1,
        parentId: 47,
        uri: "gateway/user-wise-transaction-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2022-07-19",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-10-19",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 220,
        icon: null,
        name: "Member Limit Report",
        menuCode: "",
        orderId: 2,
        parentId: 47,
        uri: "gateway/member-history-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2022-07-19",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-11-07",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 226,
        icon: null,
        name: "Pending Transaction Report",
        menuCode: "",
        orderId: 1,
        parentId: 47,
        uri: "gateway/pending-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2022-08-02",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-10-20",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 239,
        icon: "1",
        name: "Loan Payment Report",
        menuCode: "",
        orderId: 1,
        parentId: 47,
        uri: "gateway/loan-payment-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2022-10-20",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2023-08-27",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 277,
        icon: null,
        name: "Branch Wise Customer Aggregate Report",
        menuCode: "",
        orderId: 2,
        parentId: 47,
        uri: "gateway/branch-wise-customer-aggregate-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "REPORTS_",
        active: true,
        created_date: "2023-08-27",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2021-05-22",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2021-07-02",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 3,
    icon: null,
    name: "Menu Management",
    menuCode: null,
    orderId: 2,
    parentId: 0,
    uri: "gateway/menu-management",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2022-08-02",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 5,
        icon: null,
        name: "Menu Setup",
        menuCode: null,
        orderId: 2,
        parentId: 3,
        uri: "gateway/menu-management/menu",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2020-03-25",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-08-02",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 6,
        icon: null,
        name: "Menu-User Mapping",
        menuCode: null,
        orderId: 1,
        parentId: 3,
        uri: "gateway/menu-management/menu-user",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2020-03-25",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-08-02",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 75,
        icon: null,
        name: " Menu-Role Mapping",
        menuCode: null,
        orderId: 3,
        parentId: 3,
        uri: "gateway/menu-management/menu-role",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-07-05",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2020-03-25",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2021-07-02",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 73,
    icon: null,
    name: "Access Control",
    menuCode: null,
    orderId: 1,
    parentId: 0,
    uri: "access-control",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2022-08-02",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 9,
        icon: null,
        name: "Role Setup",
        menuCode: null,
        orderId: 2,
        parentId: 73,
        uri: "gateway/access-control/roles",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2020-03-25",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-08-02",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 8,
        icon: null,
        name: "User Setup",
        menuCode: null,
        orderId: 1,
        parentId: 73,
        uri: "gateway/access-control/users",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2020-03-25",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-08-02",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 10,
        icon: null,
        name: "Permission Setup",
        menuCode: null,
        orderId: 3,
        parentId: 73,
        uri: "gateway/access-control/permissions",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2020-03-25",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2021-07-02",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2021-12-22",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 123,
    icon: "1",
    name: "Remittance Provider Management",
    menuCode: "",
    orderId: 1,
    parentId: 0,
    uri: "gateway/remittance",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2021-12-22",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 125,
        icon: "1",
        name: "Client-Remit Provider Mapping",
        menuCode: "",
        orderId: 2,
        parentId: 123,
        uri: "gateway/remittance/client-remit-vendor-mapping",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-12-14",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-01-17",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 136,
        icon: "1",
        name: "Remit Scope Mapping",
        menuCode: "",
        orderId: 1,
        parentId: 123,
        uri: "gateway/remittance/user-scope-mapping",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-01-17",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-01-10",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 117,
        icon: "1",
        name: "Settlement Provider Setup",
        menuCode: "",
        orderId: 1,
        parentId: 123,
        uri: "gateway/settlement/settlement-provider-setup",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-11-11",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2021-12-22",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 124,
        icon: "1",
        name: "Remit Provider Setup ",
        menuCode: "",
        orderId: 1,
        parentId: 123,
        uri: "gateway/remittance/remit-vendor-management",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-12-14",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-09-14",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 235,
        icon: null,
        name: "Client Remit Branch Mapping",
        menuCode: "",
        orderId: 4,
        parentId: 123,
        uri: "gateway/remittance/partner-id-mapping",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-09-14",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2021-12-14",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2022-02-10",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 143,
    icon: "1",
    name: "Spot Banking Report",
    menuCode: "",
    orderId: 1,
    parentId: 0,
    uri: "gateway/",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2022-02-10",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 140,
        icon: "1",
        name: "Spot Leader Transaction Report",
        menuCode: "",
        orderId: 1,
        parentId: 143,
        uri: "gateway/spot-leader-transaction-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "SPOT_",
        active: true,
        created_date: "2022-01-25",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2022-02-10",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2022-07-29",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 131,
    icon: "1",
    name: "PKI Setup",
    menuCode: "",
    orderId: 1,
    parentId: 0,
    uri: "gateway/pki/external",
    menuType: "OUR_MENU",
    children: [],
    menuPrefix: null,
    active: true,
    created_date: "2021-12-16",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2022-02-18",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 187,
    icon: "1",
    name: "SMS Service",
    menuCode: "",
    orderId: 1,
    parentId: 0,
    uri: "gateway/sms-service",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2022-02-18",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 188,
        icon: "1",
        name: "SMS Service Provider Setup",
        menuCode: "",
        orderId: 1,
        parentId: 187,
        uri: "gateway/sms-service/sms-service-provider-setup",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-02-18",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-02-18",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 189,
        icon: "1",
        name: "SMS Service Client Mapping",
        menuCode: "",
        orderId: 1,
        parentId: 187,
        uri: "gateway/sms-service/sms-service-client-mapping",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-02-18",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2022-02-18",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2022-07-20",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 222,
    icon: "1",
    name: "Admin Reports",
    menuCode: "",
    orderId: 1,
    parentId: 0,
    uri: "gateway/",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2022-08-02",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 191,
        icon: "1",
        name: "Commission Percent Report",
        menuCode: "",
        orderId: 1,
        parentId: 222,
        uri: "gateway/commission-percent-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-03-03",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-07-20",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 203,
        icon: "1",
        name: "Transaction Billing Report",
        menuCode: "",
        orderId: 1,
        parentId: 222,
        uri: "gateway/recharge-report/transaction-billing",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-03-31",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-08-02",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 213,
        icon: null,
        name: "Overall Transaction Commission Report",
        menuCode: "",
        orderId: 1,
        parentId: 222,
        uri: "gateway/overall-trans-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-06-27",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2023-02-15",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 246,
        icon: "1",
        name: "Bulk Email Commission Report",
        menuCode: "",
        orderId: 11,
        parentId: 222,
        uri: "gateway/bulk-email-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2023-01-31",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-07-20",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 215,
        icon: "1",
        name: "Service Action Report",
        menuCode: "",
        orderId: 1,
        parentId: 222,
        uri: "gateway/service-action-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-07-11",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-07-20",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 221,
        icon: "1",
        name: "SMS Count Report",
        menuCode: "",
        orderId: 1,
        parentId: 222,
        uri: "gateway/sms-push-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-07-20",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-07-20",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 217,
        icon: null,
        name: "Vendor Wise DFS Summary Report",
        menuCode: "",
        orderId: 1,
        parentId: 222,
        uri: "gateway/vendor-wise-dfs-summary-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-07-19",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-09-09",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 223,
        icon: null,
        name: "SMS/Top-up Balance Report",
        menuCode: "",
        orderId: 1,
        parentId: 222,
        uri: "gateway/current-balance-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-07-25",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-11-30",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 216,
        icon: null,
        name: "Transaction Lookup ",
        menuCode: "",
        orderId: 1,
        parentId: 222,
        uri: "gateway/transaction-lookup-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-07-19",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-09-21",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 236,
        icon: "1",
        name: "Scheduler",
        menuCode: "",
        orderId: 1,
        parentId: 222,
        uri: "gateway/schedular",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-09-21",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-09-22",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 237,
        icon: "1",
        name: "Vendor Transaction Lookup",
        menuCode: "",
        orderId: 1,
        parentId: 222,
        uri: "gateway/vendor-transaction-lookup-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-09-22",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-08-10",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 229,
        icon: "1",
        name: "Cbs Transaction LookUp ",
        menuCode: "",
        orderId: 1,
        parentId: 222,
        uri: "gateway/cbs-lookup-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-08-10",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2023-08-21",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 276,
        icon: null,
        name: "Failed Transaction Report",
        menuCode: "",
        orderId: 2,
        parentId: 222,
        uri: "gateway/failed-transaction-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2023-08-21",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2022-07-20",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2022-08-02",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 208,
    icon: "1",
    name: "Branch User Setup",
    menuCode: "",
    orderId: 1,
    parentId: 0,
    uri: "gateway/access-control/user-setup",
    menuType: "OUR_MENU",
    children: [],
    menuPrefix: null,
    active: true,
    created_date: "2022-04-19",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2022-04-04",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 206,
    icon: "1",
    name: "SMS Rate Setup",
    menuCode: "",
    orderId: 1,
    parentId: 0,
    uri: "gateway/sms-rate-setup",
    menuType: "OUR_MENU",
    children: [],
    menuPrefix: null,
    active: true,
    created_date: "2022-04-04",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2021-04-18",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 22,
    icon: null,
    name: "Bank Transfer",
    menuCode: null,
    orderId: 1,
    parentId: 0,
    uri: "gateway/bank-transfer",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2022-07-25",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 74,
        icon: null,
        name: "Bank Setup",
        menuCode: null,
        orderId: 2,
        parentId: 22,
        uri: "gateway/bank-transfer/bank-list",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "BANKTRANSFER_",
        active: true,
        created_date: "2021-07-05",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2021-04-18",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2022-08-02",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 60,
    icon: null,
    name: "Merchant Management",
    menuCode: null,
    orderId: 1,
    parentId: 0,
    uri: ".",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2022-08-02",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 225,
        icon: null,
        name: "Merchant Setup",
        menuCode: "",
        orderId: 1,
        parentId: 60,
        uri: "gateway/merchant-management",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: "MERCHANT_",
        active: true,
        created_date: "2022-08-02",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2021-06-02",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2022-08-02",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 46,
    icon: null,
    name: "Wallet Management",
    menuCode: null,
    orderId: 1,
    parentId: 0,
    uri: "gateway/wallet-management",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2023-08-27",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 142,
        icon: null,
        name: "Credit Request",
        menuCode: "",
        orderId: 2,
        parentId: 46,
        uri: "gateway/wallet-management/credit-request",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-02-03",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2021-05-18",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2022-08-02",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 227,
    icon: null,
    name: "Member Report",
    menuCode: "",
    orderId: 1,
    parentId: 0,
    uri: "gateway/",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2022-08-02",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 194,
        icon: "1",
        name: "Member History Report",
        menuCode: "",
        orderId: 1,
        parentId: 227,
        uri: "gateway/member-limit-report",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-03-16",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2022-08-02",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2021-05-01",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 29,
    icon: null,
    name: "Company",
    menuCode: null,
    orderId: 1,
    parentId: 0,
    uri: "gateway/",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2022-08-02",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 30,
        icon: null,
        name: "Miscall Banking Setup",
        menuCode: null,
        orderId: 1,
        parentId: 29,
        uri: "gateway/miscall-banking-setup",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-05-01",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-08-10",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 31,
        icon: null,
        name: "Email Alert",
        menuCode: null,
        orderId: 2,
        parentId: 29,
        uri: "gateway/send-email-alert",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-05-01",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2021-05-01",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2022-09-14",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 234,
    icon: "1",
    name: "Dynamic Service",
    menuCode: "",
    orderId: 1,
    parentId: 0,
    uri: "gateway/",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2022-09-14",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 232,
        icon: "1",
        name: "Dynamic Service Mapping",
        menuCode: "",
        orderId: 1,
        parentId: 234,
        uri: "gateway/dynamic-service-mapping",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-09-01",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2022-09-14",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 231,
        icon: "1",
        name: "Dynamic Service Setup",
        menuCode: "",
        orderId: 1,
        parentId: 234,
        uri: "gateway/dynamic-service",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2022-09-01",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2022-09-14",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2023-05-09",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 252,
    icon: null,
    name: "Schedule Enabled Services",
    menuCode: "",
    orderId: 1,
    parentId: 0,
    uri: "gateway/schedule-enabled-services",
    menuType: "OUR_MENU",
    children: [],
    menuPrefix: null,
    active: true,
    created_date: "2023-05-09",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2023-05-29",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 254,
    icon: "1",
    name: "Mobile Setup",
    menuCode: "",
    orderId: 1,
    parentId: 0,
    uri: "gateway/",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2023-05-29",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 253,
        icon: "1",
        name: "Frequently Asked Questions",
        menuCode: "",
        orderId: 1,
        parentId: 254,
        uri: "gateway/faq-setup",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2023-05-29",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2023-06-13",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 255,
        icon: null,
        name: "Advertisement Category Setup",
        menuCode: "",
        orderId: 1,
        parentId: 254,
        uri: "gateway/mobile-setup/advertisement-category-setup",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2023-06-13",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2023-06-13",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 256,
        icon: null,
        name: "Advertisement Compose",
        menuCode: "",
        orderId: 1,
        parentId: 254,
        uri: "gateway/mobile-setup/advertisement-compose",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2023-06-13",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2023-06-27",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 260,
        icon: null,
        name: "Information Setup",
        menuCode: "",
        orderId: 4,
        parentId: 254,
        uri: "gateway/information-setup",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2023-06-27",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2023-07-06",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 261,
        icon: null,
        name: "Redirection Setup",
        menuCode: "",
        orderId: 5,
        parentId: 254,
        uri: "gateway/redirection-setup",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2023-07-06",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2023-07-09",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 262,
        icon: null,
        name: "Dispute Lodge",
        menuCode: "",
        orderId: 6,
        parentId: 254,
        uri: "gateway/dispute-lodge",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2023-07-09",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2023-05-29",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2023-06-13",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 257,
    icon: null,
    name: "Agency Setup",
    menuCode: "",
    orderId: 1,
    parentId: 0,
    uri: "gateway/mobile-setup/advertisement-agency-setup",
    menuType: "OUR_MENU",
    children: [],
    menuPrefix: null,
    active: true,
    created_date: "2023-06-13",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2023-06-19",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 258,
    icon: "30",
    name: "Privacy Policy Setup",
    menuCode: "",
    orderId: 30,
    parentId: 0,
    uri: "gateway/privacy-policy-setup",
    menuType: "OUR_MENU",
    children: [],
    menuPrefix: null,
    active: true,
    created_date: "2023-06-19",
    parent_name: "n/a",
  },
  {
    lastModifiedDate: "2023-06-20",
    createdBy: 1,
    lastModifiedBy: 1,
    id: 259,
    icon: null,
    name: "MDabali",
    menuCode: "",
    orderId: 1,
    parentId: 0,
    uri: "gateway/",
    menuType: "OUR_MENU",
    children: [
      {
        lastModifiedDate: "2023-06-20",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 33,
        icon: null,
        name: "Security TIps",
        menuCode: null,
        orderId: 1,
        parentId: 259,
        uri: "gateway/security-tips",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2021-05-01",
        parent_name: "n/a",
      },
      {
        lastModifiedDate: "2023-08-08",
        createdBy: 1,
        lastModifiedBy: 1,
        id: 272,
        icon: null,
        name: "External Mobile Message Compose",
        menuCode: "",
        orderId: 11,
        parentId: 259,
        uri: "gateway/external-mobile-message-compose",
        menuType: "OUR_MENU",
        children: null,
        menuPrefix: null,
        active: true,
        created_date: "2023-08-08",
        parent_name: "n/a",
      },
    ],
    menuPrefix: null,
    active: true,
    created_date: "2023-06-20",
    parent_name: "n/a",
  },
];

let urls = [];

for (let i in menu) {
  urls.push(menu[i].uri);
  if (menu[i]?.children.length) {
    forChildren(menu[i].children);
  }
}

function forChildren(child) {
  child.forEach((el) => {
    urls.push(el.uri);
    if (el?.children?.length) {
      forChildren(el?.children);
    }
  });
}

console.log(urls);
